concurrent = 1
check_interval = 0
connection_max_age = "15m0s"
shutdown_timeout = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "docker-runner"
  url = "https://code.swecha.org"
  token = "YOUR_DOCKER_TOKEN_HERE"
  executor = "docker"

  [runners.docker]
    image = "python:3.10"
    privileged = false
    volumes = ["/cache"]
    shm_size = 0